Seed set to 20241203
Using cache found in /root/.cache/torch/hub/facebookresearch_dinov2_main
/root/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/swiglu_ffn.py:51: UserWarning: xFormers is not available (SwiGLU)
  warnings.warn("xFormers is not available (SwiGLU)")
/root/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/attention.py:33: UserWarning: xFormers is not available (Attention)
  warnings.warn("xFormers is not available (Attention)")
/root/.cache/torch/hub/facebookresearch_dinov2_main/dinov2/layers/block.py:40: UserWarning: xFormers is not available (Block)
  warnings.warn("xFormers is not available (Block)")
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Restoring states from the checkpoint path at /workspace/text-to-image-retrivial/logs/nano_clip/version_0/checkpoints/epoch=[19]_recall@5=[0.5979]].ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "/workspace/text-to-image-retrivial/train.py", line 148, in <module>
    train(batch_size=args.bs, lr=args.lr, dim=args.dim, dev=args.dev)
  File "/workspace/text-to-image-retrivial/train.py", line 135, in train
    trainer.fit(model, train_dataloader, val_dataloader, ckpt_path="/workspace/text-to-image-retrivial/logs/nano_clip/version_0/checkpoints/epoch=[19]_recall@5=[0.5979]].ckpt")
  File "/venv/main/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/venv/main/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/main/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/venv/main/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1003, in _run
    self._checkpoint_connector.restore_training_state()
  File "/venv/main/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 309, in restore_training_state
    self.restore_optimizers_and_schedulers()
  File "/venv/main/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 375, in restore_optimizers_and_schedulers
    raise KeyError(
KeyError: 'Trying to restore optimizer state but checkpoint contains only the model. This is probably due to `ModelCheckpoint.save_weights_only` being set to `True`.'
